In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size = 10000

In [5]:
#One how Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_repr

[[8353, 3350, 2540, 3753],
 [8353, 3350, 2540, 5934],
 [8353, 1135, 2540, 9240],
 [1414, 9670, 2947, 6811, 8524],
 [1414, 9670, 2947, 6811, 6173],
 [985, 8353, 8541, 2540, 9183],
 [6806, 2206, 5207, 6811]]

In [7]:
# Word Embedding Representation which was passed to embedding layer
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 8353 3350 2540 3753]
 [   0    0    0    0 8353 3350 2540 5934]
 [   0    0    0    0 8353 1135 2540 9240]
 [   0    0    0 1414 9670 2947 6811 8524]
 [   0    0    0 1414 9670 2947 6811 6173]
 [   0    0    0  985 8353 8541 2540 9183]
 [   0    0    0    0 6806 2206 5207 6811]]


In [10]:
#feature representation
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\SIMPLE_RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


array([[[ 2.35889293e-02,  1.57375596e-02,  2.12285034e-02,
          3.99924554e-02,  8.94328207e-03, -5.29281050e-03,
          1.14041455e-02,  2.44780220e-02,  4.40623499e-02,
         -2.35766657e-02],
        [ 2.35889293e-02,  1.57375596e-02,  2.12285034e-02,
          3.99924554e-02,  8.94328207e-03, -5.29281050e-03,
          1.14041455e-02,  2.44780220e-02,  4.40623499e-02,
         -2.35766657e-02],
        [ 2.35889293e-02,  1.57375596e-02,  2.12285034e-02,
          3.99924554e-02,  8.94328207e-03, -5.29281050e-03,
          1.14041455e-02,  2.44780220e-02,  4.40623499e-02,
         -2.35766657e-02],
        [ 2.35889293e-02,  1.57375596e-02,  2.12285034e-02,
          3.99924554e-02,  8.94328207e-03, -5.29281050e-03,
          1.14041455e-02,  2.44780220e-02,  4.40623499e-02,
         -2.35766657e-02],
        [ 4.98587005e-02,  1.35137886e-03, -1.56071559e-02,
          2.21062191e-02,  1.84462219e-03,  9.10314173e-03,
         -2.67086271e-02,  4.73957546e-02, -7.728576