In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size = 10000

In [5]:
#One how Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_repr

[[8170, 5598, 5970, 9106],
 [8170, 5598, 5970, 9621],
 [8170, 2903, 5970, 4237],
 [9306, 2459, 2545, 9647, 2954],
 [9306, 2459, 2545, 9647, 6862],
 [8253, 8170, 832, 5970, 5815],
 [1084, 8888, 984, 9647]]

In [7]:
# Word Embedding Representation which was passed to embedding layer
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 8170 5598 5970 9106]
 [   0    0    0    0 8170 5598 5970 9621]
 [   0    0    0    0 8170 2903 5970 4237]
 [   0    0    0 9306 2459 2545 9647 2954]
 [   0    0    0 9306 2459 2545 9647 6862]
 [   0    0    0 8253 8170  832 5970 5815]
 [   0    0    0    0 1084 8888  984 9647]]


In [10]:
#feature representation
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 192ms/step


array([[[-0.00210007,  0.0483655 , -0.03921358, -0.03634566,
         -0.0480793 ,  0.03176606, -0.03542628,  0.01575038,
          0.00316406,  0.01273081],
        [-0.00210007,  0.0483655 , -0.03921358, -0.03634566,
         -0.0480793 ,  0.03176606, -0.03542628,  0.01575038,
          0.00316406,  0.01273081],
        [-0.00210007,  0.0483655 , -0.03921358, -0.03634566,
         -0.0480793 ,  0.03176606, -0.03542628,  0.01575038,
          0.00316406,  0.01273081],
        [-0.00210007,  0.0483655 , -0.03921358, -0.03634566,
         -0.0480793 ,  0.03176606, -0.03542628,  0.01575038,
          0.00316406,  0.01273081],
        [-0.00416641, -0.00895669, -0.01620483,  0.04830083,
          0.04700586,  0.01714963,  0.0192329 , -0.02514399,
         -0.01220038, -0.01757077],
        [-0.01850734, -0.04669699,  0.0016316 ,  0.03868597,
         -0.0106522 , -0.01205766,  0.00844508, -0.0148996 ,
         -0.0019853 , -0.04031505],
        [ 0.04398009, -0.01746202, -0.0068195 ,  0.0